#define IDC_RADIOTRAY			110

#define IDI_RADIOTRAY			120
#define IDI_PLAY				121
#define IDI_STOP    			122
#define IDI_PLAY_ERROR          123
#define IDI_LOADING_01    		124
#define IDI_LOADING_02    		125
#define IDI_LOADING_03  		126
#define IDI_LOADING_04  		127

#define IDM_EXIT                140
#define IDM_MENU_ITEM           150

#define IDS_APP_TITLE			200
#define IDS_NO_CONFIG           201
#define IDS_BUFFERING           202

#define IDS_BASS_OK             203
#define IDS_BASS_ERROR_MEM      IDS_BASS_OK + 1
#define IDS_BASS_ERROR_FILEOPEN IDS_BASS_OK + 2
#define IDS_BASS_ERROR_DRIVER   IDS_BASS_OK + 3
#define IDS_BASS_ERROR_BUFLOST  IDS_BASS_OK + 4
#define IDS_BASS_ERROR_HANDLE   IDS_BASS_OK + 5
#define IDS_BASS_ERROR_FORMAT   IDS_BASS_OK + 6
#define IDS_BASS_ERROR_POSITION IDS_BASS_OK + 7
#define IDS_BASS_ERROR_INIT     IDS_BASS_OK + 8
#define IDS_BASS_ERROR_START    IDS_BASS_OK + 9
#define IDS_BASS_ERROR_SSL      IDS_BASS_OK + 10
#define IDS_BASS_ERROR_ALREADY  IDS_BASS_OK + 11
#define IDS_BASS_ERROR_NOCHAN   IDS_BASS_OK + 12
#define IDS_BASS_ERROR_ILLTYPE  IDS_BASS_OK + 13
#define IDS_BASS_ERROR_ILLPARAM IDS_BASS_OK + 14
#define IDS_BASS_ERROR_NO3D     IDS_BASS_OK + 15
#define IDS_BASS_ERROR_NOEAX    IDS_BASS_OK + 16
#define IDS_BASS_ERROR_DEVICE   IDS_BASS_OK + 17
#define IDS_BASS_ERROR_NOPLAY   IDS_BASS_OK + 18
#define IDS_BASS_ERROR_FREQ     IDS_BASS_OK + 19
#define IDS_BASS_ERROR_NOTFILE  IDS_BASS_OK + 20
#define IDS_BASS_ERROR_NOHW     IDS_BASS_OK + 21
#define IDS_BASS_ERROR_EMPTY    IDS_BASS_OK + 22
#define IDS_BASS_ERROR_NONET    IDS_BASS_OK + 23
#define IDS_BASS_ERROR_CREATE   IDS_BASS_OK + 24
#define IDS_BASS_ERROR_NOFX     IDS_BASS_OK + 25
#define IDS_BASS_ERROR_NOTAVAIL IDS_BASS_OK + 26
#define IDS_BASS_ERROR_DECODE   IDS_BASS_OK + 27
#define IDS_BASS_ERROR_DX       IDS_BASS_OK + 28
#define IDS_BASS_ERROR_TIMEOUT  IDS_BASS_OK + 29
#define IDS_BASS_ERROR_FILEFORM IDS_BASS_OK + 30
#define IDS_BASS_ERROR_SPEAKER  IDS_BASS_OK + 31
#define IDS_BASS_ERROR_VERSION  IDS_BASS_OK + 32
#define IDS_BASS_ERROR_CODEC    IDS_BASS_OK + 33
#define IDS_BASS_ERROR_ENDED    IDS_BASS_OK + 34
#define IDS_BASS_ERROR_BUSY     IDS_BASS_OK + 35
#define IDS_BASS_ERROR_UNKNOWN  IDS_BASS_OK + 36
